import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ShoppingCart from './ShoppingCart';
import request from 'supertest';
import express from 'express';
import { cartRouter } from '../../server/routes/cart';
import { authenticate } from '../../server/middleware/auth';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Create test Express app
const createTestApp = () => {
  const app = express();
  app.use(express.json());
  app.use('/api/cart', cartRouter);
  return app;
};

describe('ShoppingCart Integration Tests', () => {
  let testUserId: string;
  let testDesignId: string;
  let testFabricId: string;
  let testGsmId: string;
  let testSizeId: string;
  let testColorId: string;
  let authToken: string;

  beforeAll(async () => {
    // Create test user
    const user = await prisma.user.create({
      data: {
        email: 'cart-test@example.com',
        password: 'hashedpassword',
        role: 'CUSTOMER',
      },
    });
    testUserId = user.id;

    // Create test design
    const design = await prisma.design.create({
      data: {
        userId: testUserId,
        prompt: 'Test design for cart',
        imageUrl: 'https://example.com/test-design.jpg',
        cloudinaryId: 'test-cloudinary-id',
        aspectRatio: '1:1',
        aiProvider: 'stability',
      },
    });
    testDesignId = design.id;

    // Get catalog options
    const fabric = await prisma.fabric.findFirst({ where: { isActive: true } });
    const gsm = await prisma.gSM.findFirst({ where: { isActive: true } });
    const size = await prisma.size.findFirst({ where: { isActive: true } });
    const color = await prisma.color.findFirst({ where: { isActive: true } });

    if (!fabric || !gsm || !size || !color) {
      throw new Error('Catalog options not found. Run seed script first.');
    }

    testFabricId = fabric.id;
    testGsmId = gsm.id;
    testSizeId = size.id;
    testColorId = color.id;

    // Mock auth token (in real scenario, this would be generated by auth service)
    authToken = 'mock-jwt-token';
  });

  afterAll(async () => {
    // Clean up test data
    await prisma.cartItem.deleteMany({ where: { userId: testUserId } });
    await prisma.design.deleteMany({ where: { userId: testUserId } });
    await prisma.user.delete({ where: { id: testUserId } });
    await prisma.$disconnect();
  });

  beforeEach(async () => {
    // Clear cart before each test
    await prisma.cartItem.deleteMany({ where: { userId: testUserId } });
  });

  describe('Cart API Integration', () => {
    it('should fetch empty cart', async () => {
      const app = createTestApp();

      const response = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(response.status).toBe(200);
      expect(response.body.cart.items).toEqual([]);
      expect(response.body.cart.totalItems).toBe(0);
      expect(response.body.cart.totalPrice).toBe(0);
    });

    it('should add item to cart', async () => {
      const app = createTestApp();

      const response = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 2,
        });

      expect(response.status).toBe(201);
      expect(response.body.item).toBeDefined();
      expect(response.body.item.quantity).toBe(2);
      expect(response.body.item.designId).toBe(testDesignId);
    });

    it('should fetch cart with items', async () => {
      const app = createTestApp();

      // Add item first
      await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 1,
        });

      // Fetch cart
      const response = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(response.status).toBe(200);
      expect(response.body.cart.items.length).toBe(1);
      expect(response.body.cart.totalItems).toBe(1);
      expect(response.body.cart.totalPrice).toBeGreaterThan(0);
    });

    it('should update cart item quantity', async () => {
      const app = createTestApp();

      // Add item
      const addResponse = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 1,
        });

      const itemId = addResponse.body.item.id;

      // Update quantity
      const updateResponse = await request(app)
        .put(`/api/cart/items/${itemId}`)
        .set('Authorization', `Bearer ${authToken}`)
        .send({ quantity: 5 });

      expect(updateResponse.status).toBe(200);
      expect(updateResponse.body.item.quantity).toBe(5);
    });

    it('should remove cart item', async () => {
      const app = createTestApp();

      // Add item
      const addResponse = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 1,
        });

      const itemId = addResponse.body.item.id;

      // Remove item
      const removeResponse = await request(app)
        .delete(`/api/cart/items/${itemId}`)
        .set('Authorization', `Bearer ${authToken}`);

      expect(removeResponse.status).toBe(200);
      expect(removeResponse.body.message).toBe('Item removed from cart successfully');

      // Verify cart is empty
      const cartResponse = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(cartResponse.body.cart.items.length).toBe(0);
    });

    it('should clear entire cart', async () => {
      const app = createTestApp();

      // Add multiple items
      await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 1,
        });

      await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 2,
        });

      // Clear cart
      const clearResponse = await request(app)
        .delete('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(clearResponse.status).toBe(200);
      expect(clearResponse.body.message).toBe('Cart cleared successfully');

      // Verify cart is empty
      const cartResponse = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(cartResponse.body.cart.items.length).toBe(0);
    });

    it('should calculate correct total price for multiple items', async () => {
      const app = createTestApp();

      // Add first item
      const item1Response = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 2,
        });

      const item1Price = item1Response.body.item.price;

      // Add second item with different quantity
      const item2Response = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 3,
        });

      const item2Price = item2Response.body.item.price;

      // Fetch cart and verify total
      const cartResponse = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(cartResponse.body.cart.totalItems).toBe(5); // 2 + 3
      expect(cartResponse.body.cart.totalPrice).toBe(item1Price + item2Price);
    });

    it('should return 401 for unauthenticated requests', async () => {
      const app = createTestApp();

      const response = await request(app).get('/api/cart');

      expect(response.status).toBe(401);
    });

    it('should validate required fields when adding item', async () => {
      const app = createTestApp();

      const response = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          // Missing other required fields
        });

      expect(response.status).toBe(400);
      expect(response.body.error).toContain('Missing required fields');
    });

    it('should validate quantity is positive integer', async () => {
      const app = createTestApp();

      const response = await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: -1,
        });

      expect(response.status).toBe(400);
      expect(response.body.error).toContain('positive integer');
    });

    it('should return 404 when updating non-existent cart item', async () => {
      const app = createTestApp();

      const response = await request(app)
        .put('/api/cart/items/non-existent-id')
        .set('Authorization', `Bearer ${authToken}`)
        .send({ quantity: 5 });

      expect(response.status).toBe(404);
      expect(response.body.error).toBe('Cart item not found');
    });

    it('should return 404 when removing non-existent cart item', async () => {
      const app = createTestApp();

      const response = await request(app)
        .delete('/api/cart/items/non-existent-id')
        .set('Authorization', `Bearer ${authToken}`);

      expect(response.status).toBe(404);
      expect(response.body.error).toBe('Cart item not found');
    });
  });

  describe('Cart Persistence', () => {
    it('should persist cart items across sessions', async () => {
      const app = createTestApp();

      // Add item in first "session"
      await request(app)
        .post('/api/cart/items')
        .set('Authorization', `Bearer ${authToken}`)
        .send({
          designId: testDesignId,
          fabricId: testFabricId,
          gsmId: testGsmId,
          sizeId: testSizeId,
          colorId: testColorId,
          quantity: 1,
        });

      // Fetch cart in second "session" (simulated by new request)
      const response = await request(app)
        .get('/api/cart')
        .set('Authorization', `Bearer ${authToken}`);

      expect(response.status).toBe(200);
      expect(response.body.cart.items.length).toBe(1);
    });
  });
});
